name = "container"
description = "A base rhel-edge container image"
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "python3"
version = "*"

[[packages]]
name = "fapolicyd"
version = "*"

[customizations.services]
enabled = ["fapolicyd"]
